apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nikhilyande/backend:latest
        env:
        - name: DB_HOST
          value: psql
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: myuser
        - name: DB_PASSWORD
          value: mypassword
        - name: DB_NAME
          value: base
        ports:
        - containerPort: 8081
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_PASSWORD
          value: mypassword
        - name: POSTGRES_DB
          value: base
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        emptyDir: {}